Aerolinea/Controllers/AvionController.cs
using Aerolinea.DA;
using Aerolinea.DA.Entities;
using Aerolinea.Models;
using Aerolinea.Models.MostrarViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aerolinea.Controllers
{
    public class AvionController : Controller
    {
        private AerolineaContext db = new AerolineaContext();
        Logic lg = new Logic();
        
        #region get methods

        public ActionResult RegistrarAvion()
        {
            var model = new RegistrarAvionViewModel();
            model.NumSerie = lg.GenerarNSerie(9);
            return View(model);
        }

        public ActionResult EliminarAvion(int id)
        {
            var Avion = db.avion.SingleOrDefault(x => x.AvionID == id);
            db.avion.Attach(Avion);
            db.avion.Remove(Avion);
            db.SaveChanges();
            return RedirectToAction("MostrarAviones");
        }

        public ActionResult ActualizarAvion(int id)
        {
            var model = new RegistrarAvionViewModel();
            //var modelActu = db.avion.SingleOrDefault(x => x.AvionID == id);
            //model.NumSerie = modelActu.NumSerie;
            //model.Modelo = modelActu.Modelo;
            //model.Capacidad = modelActu.Capacidad;
            return View(model);
        }

        public ActionResult MostrarAviones()
        {
            var model = new MostrarAvionesViewModel();
            model.listAvi = db.avion.ToList();
            return View(model);
        }

        #endregion

        #region post methods

        [HttpPost]
        public ActionResult RegistrarAvion(RegistrarAvionViewModel model)
        {
            //var avion = new Avion
            //{
            //    NumSerie = model.NumSerie,
            //    Modelo = model.Modelo,
            //    Capacidad = model.Capacidad
            //};
            //db.avion.Add(avion);
            //db.SaveChanges();
            return RedirectToAction("MostrarAviones");
        }

        [HttpPost]
        public ActionResult ActualizarAvion(RegistrarAvionViewModel model)
        {
            //var Avion = db.avion.SingleOrDefault(x => x.NumSerie == model.NumSerie);
            //Avion.Modelo = model.Modelo;
            //Avion.NumSerie = model.NumSerie;
            //Avion.Capacidad = model.Capacidad;
            //db.Entry(Avion).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return RedirectToAction("MostrarAviones");
        }

        #endregion
    }
}

Aerolinea/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aerolinea.Models.UsuarioViewModel;
using Aerolinea.DA;
using Aerolinea.Models;
using Aerolinea.Models.HomeViewModels;
using Aerolinea.Models.UsuarioViewModels;
using Aerolinea.DA.Entities;
using Aerolinea.Models.MostrarViewModels;
using Aerolinea.Models.AdministrarViewModels;

namespace Aerolinea.Controllers
{
    public class UsuarioController : Controller
    {
        AerolineaContext db = new AerolineaContext();
        Logic lg = new Logic();

        #region get methods

        public ActionResult IniciarSesion()
        {
            var model = new IniciarSesionViewModel();
            return View(model);
        }

        //public ActionResult CerrarSesion()
        //{
        //    lg.SetUserType(0);
        //    return View("../Home/Index", new IndexViewModel());
        //}

        public ActionResult RegistrarUsuario()
        {
            var model = new RegistrarUsuarioViewModel();
            model.correo = "@";
            model.contrasena = "";
            model.rol = 0;
            return View(model);
        }

        public ActionResult ActualizarUsuario(int id)
        {
            //var Usuario = db.usuario.SingleOrDefault(x => x.UsuarioID == id);
            var model = new RegistrarUsuarioViewModel();
            //model.correo = Usuario.Correo;
            //model.contrasena = Usuario.Contrasena;
            //model.rol = 0;
            return View("RegistrarUsuario", model);
        }

        public ActionResult RegistrarUsuarioSysAdmin()
        {
            if (lg.GetUserType() != 0)
            {
                return View("RegistrarUsuario");
            }
            return RedirectToAction("../Home/Index");
        }

        public ActionResult RegistrarUsuarioAgenteAero()
        {
            if (lg.GetUserType() != 0)
            {
                return View("RegistrarUsuario");
            }
            return RedirectToAction("../Home/Index");
        }

        public ActionResult RegistrarUsuarioEstandar()
        {
           return View("RegistrarUsuario");
        }

        public ActionResult RecuperarContrasena()
        {
            return View();
        }

        public ActionResult DesactivarUsuario(int id)
        {
            //var Usuario = db.usuario.SingleOrDefault(x => x.UsuarioID == id);
            //Usuario.Estado = 0;
            //db.Entry(Usuario).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            //return RedirectToAction(lg.ObtenerDireccionListaUsuario(Usuario.Rol));
            return View();
        }

        public ActionResult ActivarUsuario(int id)
        {
            //var Usuario = db.usuario.SingleOrDefault(x => x.UsuarioID == id);
            //Usuario.Estado = 1;
            //db.Entry(Usuario).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            //return RedirectToAction(lg.ObtenerDireccionListaUsuario(Usuario.Rol));
            return View();
        }

        public ActionResult ListaUsuariosSys()
        {
            var model = new MostrarUsuariosViewModel();
            model.listUsers = db.usuario.ToList();
            return View("ListaUsuarios", model);
        }

        public ActionResult ListaUsuariosAdminAero()
        {
            return View("ListaUsuarios", lg.ObtenerListaUsuarios(2));
        }

        public ActionResult ListaUsuariosAgenteAero()
        {
            return View("ListaUsuarios", lg.ObtenerListaUsuarios(3));
        }


        #endregion

        #region post methods

        //[HttpPost]
        //public ActionResult IniciarSesion(IniciarSesionViewModel model)
        //{
        //    var User = db.usuario.SingleOrDefault(x => x.Correo == model.Correo);

        //    if (User != null && User.Estado != 0)
        //    {
        //        if (User.Correo.Equals(model.Correo) && User.Contrasena.Equals(model.Contrasena))
        //        {
        //            var Usuario = db.usuario.SingleOrDefault(x => x.Correo.Equals(model.Correo));
        //            var indexModel = new IndexViewModel();
        //            lg.SetUserType(Usuario.Rol);
        //            lg.SetDisplay(Usuario.Correo);
        //            return View("../Home/Index", indexModel);
        //        }
        //    }
        //    return View("IniciarSesion");
        //}

        [HttpPost]
        public ActionResult RecuperarContrasena(RecuperarContrasenaViewModel model)
        {
            var usuario = db.usuario.SingleOrDefault(user => user.Correo.Equals(model.Correo));
            if (usuario != null)
            {
                //lg.EnviarCorreo(model.Correo, usuario.Contrasena);
                ////mensaje de se ha enviado el correo
                //return View("../Home/Index");
            }
            return RedirectToAction("RecuperarContrasena");
            //mensaje el correo digitado no se encuentra regitrado en el sistema
        }

        [HttpPost]
        public ActionResult ActualizarUsuario(RegistrarUsuarioViewModel model)
        {
            //var Usuario = db.usuario.SingleOrDefault(x => x.Correo.Equals(model.correo));
            //Usuario.Correo = model.correo;
            //Usuario.Contrasena = model.contrasena;
            //if (lg.GetUserType() == 1)
            //{
            //    Usuario.Rol = model.rol;
            //}
            //db.Entry(Usuario).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            //return RedirectToAction(lg.ObtenerDireccionListaUsuario(Usuario.Rol));
            return View();
        }

        [HttpPost]
        public ActionResult RegistrarUsuarioSysAdmin(RegistrarUsuarioViewModel model)
        {
            var usuario = new Usuario
            {
                //Correo = model.correo,
                //Contrasena = model.contrasena,
                //Estado = 1,
                //Rol = model.rol
            };
            db.usuario.Add(usuario);
            db.SaveChanges();
            return RedirectToAction("RegistrarPasajero");
        }

        [HttpPost]
        public ActionResult RegistrarUsuarioAgenteAero(RegistrarUsuarioViewModel model)
        {
            var usuario = new Usuario
            {
                //Correo = model.correo,
                //Contrasena = model.contrasena,
                //Estado = 1,
                //Rol = 3
            };
            db.usuario.Add(usuario);
            db.SaveChanges();
            return RedirectToAction("RegistrarPasajero");
        }

        [HttpPost]
        public ActionResult RegistrarUsuarioEstandar(RegistrarUsuarioViewModel model)
        {
            var usuario = new Usuario
            {
                //Correo = model.correo,
                //Contrasena = model.contrasena,
                //Estado = 1,
                //Rol = 4
            };
            db.usuario.Add(usuario);
            db.SaveChanges();
            lg.SetUsuarioID(usuario.Correo);
            return RedirectToAction("RegistrarPasajero");
        }
        #endregion
    }
}

Aerolinea/Controllers/VueloController.cs
using Aerolinea.DA;
using Aerolinea.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aerolinea.DA.Entities;
using Aerolinea.Models.MostrarViewModels;

namespace Aerolinea.Controllers
{
    public class VueloController : Controller
    {
        private AerolineaContext db = new AerolineaContext();
        private Logic log = new Logic();

        #region get methods

        public ActionResult RegistrarVuelo()
        {
            var model = new RegistrarVueloViewModel();
            var LocalListAvi = new List<SelectListItem>();
            var LocalListPais = new List<SelectListItem>();

            model.Codigo = log.GenerarCodigo(3);

            var Aviones = db.avion.ToList();
            foreach (var avion in Aviones)
            {
                LocalListAvi.Add(new SelectListItem() { Value = avion.AvionID.ToString(), Text = avion.Modelo.ToString() });
            }

            var Paises = db.pais.ToList();
            foreach (var pais in Paises)
            {
                LocalListPais.Add(new SelectListItem() { Value = pais.PaisID.ToString(), Text = pais.Nombre });
            }

            model.listaItemsAviones = LocalListAvi;
            model.listaItemsPaises = LocalListPais;
            return View(model);
        }

        public ActionResult EliminarVuelo(int id)
        {
            var Vuelo = db.vuelo.SingleOrDefault(x => x.VueloID == id);
            db.vuelo.Attach(Vuelo);
            db.vuelo.Remove(Vuelo);
            db.SaveChanges();
            return RedirectToAction("MostrarVuelos");
        }

        public ActionResult ActualizarVuelo(int id)
        {
            var Vuelo = db.vuelo.SingleOrDefault(x => x.VueloID == id);

            var model = new RegistrarVueloViewModel();
            var LocalListAvi = new List<SelectListItem>();
            var LocalListPais = new List<SelectListItem>();

            //model.Codigo = Vuelo.Codigo;
            //model.Fecha = Vuelo.Fecha;
            model.Cupo = Vuelo.Cupo;
            model.HoraLlegada = Vuelo.HoraLlegada;
            model.HoraSalida = Vuelo.HoraSalida;

            var Aviones = db.avion.ToList();
            foreach (var avion in Aviones)
            {
                LocalListAvi.Add(new SelectListItem() { Value = avion.AvionID.ToString(), Text = avion.Modelo.ToString() });
            }

            var Paises = db.pais.ToList();
            foreach (var pais in Paises)
            {
                LocalListPais.Add(new SelectListItem() { Value = pais.PaisID.ToString(), Text = pais.Nombre });
            }

            model.listaItemsAviones = LocalListAvi;
            model.listaItemsPaises = LocalListPais;
            return View(model);
        }

        public ActionResult MostrarVuelos()
        {
            var model = new MostrarVuelosViewModel();
            model.ListVuelos = db.vuelo.ToList();
            return View(model);
        }

        #endregion

        #region post methods 

        [HttpPost]
        public ActionResult RegistrarVuelo(RegistrarVueloViewModel model)
        {
            //var Avion = db.avion.SingleOrDefault(avion => avion.AvionID == model.Avion);
            //var Destino = db.pais.SingleOrDefault(pais => pais.PaisID == model.Destino);
            //var Cupo = Avion.Capacidad;

            var Vuelo = new Vuelo
            {
                Codigo = model.Codigo,
                Destino = Destino,
                Fecha = model.Fecha,
                HoraSalida = model.HoraSalida,
                HoraLlegada = model.HoraLlegada,
                Avion = Avion,
                Cupo = Cupo
            };
            db.vuelo.Add(Vuelo);
            db.SaveChanges();
            return RedirectToAction("MostrarVuelos");
        }

        [HttpPost]
        public ActionResult ActualizarVuelo(RegistrarVueloViewModel model)
        {
            //var Avion = db.avion.SingleOrDefault(x => x.AvionID == model.Avion);
            //var Destino = db.pais.SingleOrDefault(x => x.PaisID == model.Destino);
            //var Vuelo = db.vuelo.SingleOrDefault(x => x.Codigo == model.Codigo);

            //Vuelo.Codigo = model.Codigo;
            //Vuelo.Fecha = model.Fecha;
            //Vuelo.HoraLlegada = model.HoraLlegada;
            //Vuelo.HoraSalida = model.HoraSalida;
            //Vuelo.Cupo = model.Cupo;
            //Vuelo.Avion = Avion;
            //Vuelo.Destino = Destino;
            //db.Entry(Vuelo).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return RedirectToAction("MostrarVuelos");
        }

        #endregion

    }
}

Aerolinea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Aeropuerto", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vuelos", "MostrarVuelos", "Vuelos")</li>
                    <li>@Html.ActionLink("Acerca", "About", "Home")</li>
                    <li>@Html.ActionLink("Contactenos", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
        @RenderBody()
        <hr />
    <div class="container body-content">
        <footer>
            <p>&copy; @DateTime.Now.Year - Pluricode</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Aerolinea/Views/Shared/_LayoutAeroAdmin.cshtml
@using Aerolinea.Models
@{
    Logic lg = new Logic();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/StyleAeroAdmin.css" />
    <title>@ViewBag.Title</title>

</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center"><h1> <b>Orange Airlines</b> <br />@ViewBag.Title</h1></div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <ul class="nav nav-pills nav-justified">
                    <li role="presentation" class="btn-link">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Vuelos", "ListaVuelos", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Aviones", "ListaAviones", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Agentes de Ventas ", "ListaUsuariosAgenteAero", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink(@lg.GetDisplay(), "ActualizarPasajero", "Administrar", new { id = @lg.GetPassengerID() }, null)</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Admin Aerolinea - Salir", "CerrarSesion", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="text-center col-md-10 col-md-offset-1">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Aerolinea/Views/Shared/_LayoutAgente.cshtml
@using Aerolinea.Models
@{
    Logic lg = new Logic();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/StyleAgente.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center"><h1> <b>Orange Airlines</b> <br />@ViewBag.Title</h1></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <ul class="nav nav-pills nav-justified">
                    <li role="presentation" class="btn-link">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Vuelos", "ListaVuelos", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Aviones", "ListaAviones", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Reservas", "ListaReservas", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("RegistrarPasajero", "RegistrarUsuarioEstandar", "Usuario")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink(@lg.GetDisplay(), "ActualizarPasajero", "Administrar", new { id = @lg.GetPassengerID() }, null)</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Agente Aero - Salir", "CerrarSesion", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="text-center col-md-10 col-md-offset-1">
            @RenderBody()
        </div>
    </div>
</body>
</html>
@*<div id="Header">
        <div id="logo">
            @Html.ActionLink("Orange Sky", "Index", "Home");
        </div>
        <div id="navMenu">
            <ul id="menu">
                <li>
                    <a>Vuelos</a>
                    <ul>
                        <li>@Html.ActionLink("Ver Lista", "ListaVuelos", "Mostrar")</li>
                    </ul>
                </li>
                <li>
                    <a>Aviones</a>
                    <ul>
                        <li>@Html.ActionLink("Ver Lista", "ListaAviones", "Mostrar")</li>
                    </ul>
                </li>
                <li>
                    <a>Reserva</a>
                    <ul>
                        <li>@Html.ActionLink("Ver Lista", "ListaReservas", "Mostrar")</li>
                        <li>@Html.ActionLink("Registrar", "RegistrarReserva", "Administrar")</li>
                    </ul>
                </li>
            </ul>
        </div>
        <div id="SystemLog">
            @Html.ActionLink("Agente Aerolinea salir", "CerrarSesion", "Usuario")
        </div>
    </div>
    @RenderBody()*@

Aerolinea/Views/Shared/_LayoutEstandar.cshtml
@using Aerolinea.Models
@{
    Logic lg = new Logic();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/StylesEstandar.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center"><h1>@ViewBag.Title</h1></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <ul class="nav nav-pills nav-justified">
                    <li role="presentation" class="btn-link">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Vuelos", "ListaVuelos", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Reservaciones", "ListaReservas", "Mostrar")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink(@lg.GetDisplay(), "ActualizarPasajero", "Administrar", new { id = @lg.GetPassengerID() }, null)</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Salir", "CerrarSesion", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="text-center col-md-10 col-md-offset-1">
            @RenderBody()
        </div>
    </div>


    @*<div id="Header">
                <div id="logo">
                    @Html.ActionLink("Orange Sky", "Index", "Home");
                </div>
                <div id="navMenu">
                    <ul>
                        <li>@Html.ActionLink("Vuelos", "ListaVuelos", "Mostrar")</li>
                    </ul>
                </div>
            </div>
        @RenderBody()*@
</body>
</html>

Aerolinea/Views/Shared/_LayoutLogOff.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/Content/StyleLogOff.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <title>@ViewBag.Title</title>
    
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center"><h1> <b>Orange Airlines</b> <br />@ViewBag.Title</h1></div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <ul class="nav nav-pills nav-justified">
                    <li role="presentation" class="btn-link">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Vuelos", "MostrarVuelos", "Vuelo")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Registrarse", "RegistrarUsuarioEstandar", "Usuario")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Iniciar sesion", "IniciarSesion", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="text-center col-md-10 col-md-offset-1">
            @RenderBody()
        </div>
    </div>

</body>
</html>

Aerolinea/Views/Shared/_LayoutSysAdmin.cshtml
@using Aerolinea.Models
@{
    Logic lg = new Logic();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/StyleSysAdmin.css" />
    <title>@ViewBag.Title</title>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center"><h1> <b>Orange Airlines</b> <br />@ViewBag.Title</h1></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <ul class="nav nav-pills nav-justified">
                    <li role="presentation" class="btn-link">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Vuelos", "MostrarVuelos", "Vuelo")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Aviones", "MostrarAviones", "Avion")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Usuarios", "MostrarUsuariosSys", "Usuario")</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink(@lg.GetDisplay(), "ActualizarPasajero", "Usuario", new { id = @lg.GetPassengerID() }, null)</li>
                    <li role="presentation" class="btn-link">@Html.ActionLink("Admin Sistema - Salir", "CerrarSesion", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="text-center col-md-10 col-md-offset-1">
            @RenderBody()
        </div>
    </div>
</body>
</html>
@*<div id="Header">
    <div id="logo">
        @Html.ActionLink("Orange Sky", "Index", "Home");
    </div>
    <div id="navMenu">
        <ul id="menu">
            <li>
                <a>Vuelos</a>
                <ul>
                    <li>@Html.ActionLink("Ver Lista", "ListaVuelos", "Mostrar")</li>
                    <li>@Html.ActionLink("Registrar", "RegistrarVuelo", "Administrar")</li>
                </ul>
            </li>
            <li>
                <a>Aviones</a>
                <ul>
                    <li>@Html.ActionLink("Ver Lista", "ListaAviones", "Mostrar")</li>
                    <li>@Html.ActionLink("Registrar", "RegistrarAvion", "Administrar")</li>
                </ul>
            </li>
            <li>
                <a>Reservas</a>
                <ul>
                    <li>@Html.ActionLink("Ver Lista", "ListaReservas", "Mostrar")</li>
                    <li>@Html.ActionLink("Registrar", "RegistrarReserva", "Administrar")</li>
                </ul>
            </li>
            <li>
                <a>Cuentas Agente</a>
                <ul>
                    <li>@Html.ActionLink("Ver Lista", "ListaCuentasAgt", "Mostrar")</li>
                    <li>@Html.ActionLink("Registrar", "RegistrarCuentaAgt", "Administrar")</li>
                </ul>
            </li>
            <li>
                <a>Cuentas Administrador Aero</a>
                <ul>
                    <li>@Html.ActionLink("Ver Lista", "ListaCuentasAero", "Mostrar")</li>
                    <li>@Html.ActionLink("Registrar", "RegistrarCuentaAero", "Administrar")</li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="SystemLog">
        @Html.ActionLink("Administrador Sistema salir", "CerrarSesion", "Usuario")
    </div>
</div>
@RenderBody()
</body>
</html>*@