Aerolinea/Models/ReservaViewModels/MostrarReservasViewModel.cs
using Aerolinea.DA.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aerolinea.Models.MostrarViewModels
{
    public class MostrarReservasViewModel
    {
        public List<Reserva> ListReservas { set; get; }
    }
}

Aerolinea/Models/ReservaViewModels/RegistrarReservaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aerolinea.Models
{
    public class RegistrarReservaViewModel
    {
        public List<SelectListItem> listaItemsVuelos { set; get; }
        public List<SelectListItem> listaItemsPasajeros { set; get; }

        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name = "Codigo")]
        public string Codigo { set; get; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name = "Vuelo")]
        public int Vuelo { set; get; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name ="Pasajero")]
        public int Pasajero { set; get; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name ="Estado")]
        public string Estado { set; get; }
    }
}

Aerolinea/Controllers/ReservaController.cs
using Aerolinea.DA;
using Aerolinea.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aerolinea.DA.Entities;
using Aerolinea.Models.MostrarViewModels;

namespace Aerolinea.Controllers
{
    public class ReservaController : Controller
    {
        private AerolineaContext db = new AerolineaContext();
        private Logic log = new Logic();

        #region get methods

        public ActionResult RegistrarReserva()
        {
            var model = new RegistrarReservaViewModel();
            var LocalListVuelos = new List<SelectListItem>();
            var LocalListPasajeros = new List<SelectListItem>();

            model.Codigo = log.GenerarCodigo(4);

            var Vuelos = db.vuelo.ToList();
            foreach (var vuelo in Vuelos)
            {
                //LocalListVuelos.Add(new SelectListItem { Value = vuelo.VueloID.ToString(), Text = vuelo.Codigo + "//" + vuelo.Destino.Nombre + "//" + vuelo.Fecha });
            }
            model.listaItemsVuelos = LocalListVuelos;

            //var Pasajeros = db.pasajero.ToList();
            //foreach (var pasajero in Pasajeros)
            //{
            //    LocalListPasajeros.Add(new SelectListItem { Value = pasajero.PasajeroID.ToString(), Text = pasajero.NumeroPasaporte + "//" + pasajero.Nombre });
            //}
            //model.listaItemsPasajeros = LocalListPasajeros;

            return View(model);
        }

        public ActionResult EliminarReserva(int id)
        {
            var Reserva = db.reserva.SingleOrDefault(x => x.ReservaID == id);
            db.reserva.Attach(Reserva);
            db.reserva.Remove(Reserva);
            db.SaveChanges();
            return RedirectToAction("MostrarReservas");
        }

        public ActionResult ActualizarReserva(int id)
        {
            var Reserva = db.reserva.SingleOrDefault(x => x.ReservaID == id);

            var model = new RegistrarReservaViewModel();
            //var LocalListVuelos = new List<SelectListItem>();
            //var LocalListPasajeros = new List<SelectListItem>();

            //model.Codigo = Reserva.Codigo;
            //model.Estado = Reserva.Estado;

            //var Vuelos = db.vuelo.ToList();
            //foreach (var vuelo in Vuelos)
            //{
            //    LocalListVuelos.Add(new SelectListItem { Value = vuelo.VueloID.ToString(), Text = vuelo.Codigo + "//" + vuelo.Destino.Nombre + "//" + vuelo.Fecha });
            //}
            //model.listaItemsVuelos = LocalListVuelos;

            //var Pasajeros = db.pasajero.ToList();
            //foreach (var pasajero in Pasajeros)
            //{
            //    LocalListPasajeros.Add(new SelectListItem { Value = pasajero.PasajeroID.ToString(), Text = pasajero.NumeroPasaporte + "//" + pasajero.Nombre });
            //}
            //model.listaItemsPasajeros = LocalListPasajeros;

            return View(model);
        }

        public ActionResult MostrarReservas()
        {
            var model = new MostrarReservasViewModel();
            //string display = log.GetDisplay();
            //var usuario = db.usuario.SingleOrDefault(x => x.Correo == display);
            //var pasajero = db.pasajero.SingleOrDefault(x => x.Usuario.UsuarioID == usuario.UsuarioID);
            //var ListaReservas = db.reserva.ToList();
            //if (log.GetUserType() == 4)
            //{
            //    var ListaTemp = new List<Reserva>();

            //    foreach (var reserva in ListaReservas)
            //    {
            //        if (reserva.Pasajero.PasajeroID == pasajero.PasajeroID)
            //        {
            //            ListaTemp.Add(reserva);
            //        }
            //    }
            //    ListaReservas = ListaTemp;
            //}

            //model.ListReservas = ListaReservas;

            return View(model);
        }

        #endregion

        #region post methods

        [HttpPost]
        public ActionResult RegistrarReserva(RegistrarReservaViewModel model)
        {
            var Vuelo = db.vuelo.SingleOrDefault(x => x.VueloID == model.Vuelo);
            //var Pasajero = new Pasajero();
            //if (log.GetUserType() != 4)
            //{
            //    Pasajero = db.pasajero.SingleOrDefault(x => x.PasajeroID == model.Pasajero);
            //}
            //else
            //{
            //    string display = log.GetDisplay();
            //    var Usuario = db.usuario.SingleOrDefault(x => x.Correo == display);
            //    Pasajero = db.pasajero.SingleOrDefault(x => x.Usuario.UsuarioID == Usuario.UsuarioID);
            //}

            ////se elimino un cupo en el vuelo
            //Vuelo.Cupo = Vuelo.Cupo - 1;

            //var Reserva = new Reserva()
            //{
            //    Codigo = log.GenerarCodigo(4),
            //    Vuelo = Vuelo,
            //    Pasajero = Pasajero,
            //    Estado = model.Estado
            //};
            //db.reserva.Add(Reserva);
            //db.Entry(Vuelo).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return RedirectToAction("MostrarReservas");
        }

        [HttpPost]
        public ActionResult ActualizarReserva(RegistrarReservaViewModel model)
        {
            //var Reserva = db.reserva.SingleOrDefault(x => x.Codigo == model.Codigo);
            //var Vuelo = db.vuelo.SingleOrDefault(x => x.VueloID == model.Vuelo);
            //var Pasajero = db.pasajero.SingleOrDefault(x => x.PasajeroID == model.Pasajero);

            //Reserva.Codigo = model.Codigo;
            //Reserva.Estado = model.Estado;
            //db.Entry(Reserva).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return RedirectToAction("MostrarReservas");
        }

        #endregion
    }
}

Aerolinea/Views/Reserva/ActualizarReserva.cshtml
@model Aerolinea.Models.RegistrarReservaViewModel
@using Aerolinea.Models;
@{
    ViewBag.Title = "Lista de Reserva";
    Logic lg = new Logic();
    Layout = lg.ObtenerLayout(lg.GetUserType());
}

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="form-horizontal" role="form">
            <fieldset>
                <legend>Detalles de la reserva</legend>
                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Codigo, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Codigo, new { Value = Model.Codigo, @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Vuelo, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Vuelo, new SelectList(Model.listaItemsVuelos, "Value", "Text"), "Seleccione un vuelo", new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Pasajero, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Pasajero, new SelectList(Model.listaItemsPasajeros, "Value", "Text"), "Seleccione un Pasajero", new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Estado, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Estado, new { Value = Model.Estado, @class = "form-control", @placeholder = "Estado de la reserva.." })
                    </div>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Actualizar" />
                </div>
            </fieldset>
        </div>
    }
</div>

Aerolinea/Views/Reserva/MostrarReservas.cshtml
@model Aerolinea.Models.MostrarViewModels.MostrarReservasViewModel
@using Aerolinea.Models;
@{
    ViewBag.Title = "Lista de Reservas";
    Logic lg = new Logic();
    Layout = lg.ObtenerLayout(lg.GetUserType());
}

<div>
    <h3>Reservas</h3>
    @{
        if (lg.GetUserType() != 0)
        {
            <div class="jumbotron">
                @Html.ActionLink("Reservar Vuelo", "RegistrarReserva", "Administrar")
            </div>


            if (Model.ListReservas.Count == 0)
            {
                <div class="jumbotron">
                    <div class="text-danger">
                        <p>No hay reservas disponibles</p>
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-md-10 col-lg-offset-1">
                        <div class="table-responsive">
                            <table class="table table-condensed table-hover table-bordered table-condensed">
                                <tr class="text-center active">
                                    <th>Pasajero</th>
                                    <th>Vuelo</th>
                                    <th>Estado</th>
                                    <th>Actualizar</th>
                                    <th>Eliminar</th>
                                </tr>
                                @foreach (var reserva in Model.ListReservas)
                                {
                                    <tr>
                                        <td>@reserva.Pasajero.Nombre</td>
                                        <td>@reserva.Vuelo.Codigo</td>
                                        <td>@reserva.Estado</td>
                                        <td>@Html.ActionLink("Editar", "ActualizarReserva", "Reserva", new { id = reserva.ReservaID }, null)</td>
                                        <td>@Html.ActionLink("Eliminar", "EliminarReserva", "Reserva", new { id = reserva.ReservaID }, null)</td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <p>Inicie sesion para realizar esta accion</p>
        }
    }
</div>

Aerolinea/Views/Reserva/RegistrarReserva.cshtml
@model Aerolinea.Models.RegistrarReservaViewModel
@using Aerolinea.Models;
@{
    ViewBag.Title = "Registrar Reserva";
    Logic lg = new Logic();
    Layout = lg.ObtenerLayout(lg.GetUserType());
}

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="form-horizontal" role="form">
            <fieldset>
                <legend>Detalles de la reserva</legend>
                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Codigo, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Codigo, new { Value = Model.Codigo, @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>

                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Vuelo, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Vuelo, new SelectList(Model.listaItemsVuelos, "Value", "Text"), "Seleccione un vuelo", new { @class = "form-control" })
                    </div>
                </div>

                @if (lg.GetUserType() != 4)
                {
                    <div class="form-group col-md-offset-2">
                        @Html.LabelFor(model => model.Pasajero, new { @class = "control-label col-md-5" })
                        <div class="col-md-3">
                            @Html.DropDownListFor(model => model.Pasajero, new SelectList(Model.listaItemsPasajeros, "Value", "Text"), "Seleccione un Pasajero", new { @class = "form-control" })
                        </div>
                    </div>
                }

                <div class="form-group col-md-offset-2">
                    @Html.LabelFor(model => model.Estado, new { @class = "control-label col-md-5" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Estado, new { @class = "form-control", @placeholder = "Estado de la reserva.." })
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Registrar" />
                </div>
            </fieldset>
        </div>
    }
</div>