Aerolinea/Models/AvionViewModels/MostrarAvionesViewModel.cs
using Aerolinea.DA.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aerolinea.Models.MostrarViewModels
{
    public class MostrarAvionesViewModel
    {
        public List<Avion> listAvi { set; get; }
    }
}

Aerolinea/Models/AvionViewModels/RegistrarAvionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aerolinea.Models
{
    public class RegistrarAvionViewModel : Logic
    {
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name = "Numero de Serie")]
        public int NumSerie { set; get; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name ="Nombre/Modelo")]
        public string Modelo { set; get; }
        [Required(ErrorMessage = "Este campo es obligatorio.")]
        [Display(Name ="Capacidad")]
        public int Capacidad { set; get; }
    }
}

Aerolinea/Controllers/AsientoController.cs
using Aerolinea.DA;
using Aerolinea.DA.Entities;
using Aerolinea.Models;
using Aerolinea.Models.AdministrarViewModels;
using Aerolinea.Models.MostrarViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aerolinea.Controllers
{
    public class AsientoController : Controller
    {
        private AerolineaContext db = new AerolineaContext();
        private Logic log = new Logic();

        #region get methods

        public ActionResult RegistrarAsiento()
        {
            var model = new RegistrarAsientoViewModel();
            var lista = new List<SelectListItem>();
            var aviones = db.avion.ToList();
            foreach (var avion in aviones)
            {
                lista.Add(new SelectListItem() { Value = avion.AvionID.ToString(), Text = avion.Modelo.ToString() });
            }
            model.ListaItems = lista;
            return View(model);
        }

        public ActionResult EliminarAsiento(int id)
        {
            var Asiento = db.asiento.SingleOrDefault(asiento => asiento.AsientoID == id);
            db.asiento.Attach(Asiento);
            db.asiento.Remove(Asiento);
            db.SaveChanges();
            return RedirectToAction("MostrarAsientos");
        }

        public ActionResult MostrarAsientos (int id)
        {
            var model = new MostrarAsientosViewModel();
            model.avion = db.avion.SingleOrDefault(avion => avion.AvionID == id);
            return View(model);
        }

        #endregion

        #region post methods

        [HttpPost]
        public ActionResult RegistrarAsiento(RegistrarAsientoViewModel model)
        {
            return RedirectToAction("MostrarAsientos");
        }

        #endregion

    }
}

Aerolinea/Controllers/AvionController.cs
using Aerolinea.DA;
using Aerolinea.DA.Entities;
using Aerolinea.Models;
using Aerolinea.Models.MostrarViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aerolinea.Controllers
{
    public class AvionController : Controller
    {
        private AerolineaContext db = new AerolineaContext();
        Logic lg = new Logic();
        
        #region get methods

        public ActionResult RegistrarAvion()
        {
            var model = new RegistrarAvionViewModel();
            model.NumSerie = lg.GenerarNSerie(9);
            return View(model);
        }

        public ActionResult EliminarAvion(int id)
        {
            var Avion = db.avion.SingleOrDefault(x => x.AvionID == id);
            db.avion.Attach(Avion);
            db.avion.Remove(Avion);
            db.SaveChanges();
            return RedirectToAction("MostrarAviones");
        }

        public ActionResult ActualizarAvion(int id)
        {
            var model = new RegistrarAvionViewModel();
            //var modelActu = db.avion.SingleOrDefault(x => x.AvionID == id);
            //model.NumSerie = modelActu.NumSerie;
            //model.Modelo = modelActu.Modelo;
            //model.Capacidad = modelActu.Capacidad;
            return View(model);
        }

        public ActionResult MostrarAviones()
        {
            var model = new MostrarAvionesViewModel();
            model.listAvi = db.avion.ToList();
            return View(model);
        }

        #endregion

        #region post methods

        [HttpPost]
        public ActionResult RegistrarAvion(RegistrarAvionViewModel model)
        {
            //var avion = new Avion
            //{
            //    NumSerie = model.NumSerie,
            //    Modelo = model.Modelo,
            //    Capacidad = model.Capacidad
            //};
            //db.avion.Add(avion);
            //db.SaveChanges();
            return RedirectToAction("MostrarAviones");
        }

        [HttpPost]
        public ActionResult ActualizarAvion(RegistrarAvionViewModel model)
        {
            //var Avion = db.avion.SingleOrDefault(x => x.NumSerie == model.NumSerie);
            //Avion.Modelo = model.Modelo;
            //Avion.NumSerie = model.NumSerie;
            //Avion.Capacidad = model.Capacidad;
            //db.Entry(Avion).State = System.Data.Entity.EntityState.Modified;
            //db.SaveChanges();
            return RedirectToAction("MostrarAviones");
        }

        #endregion
    }
}

Aerolinea/Views/Avion/ActualizarAvion.cshtml
@model Aerolinea.Models.RegistrarAvionViewModel
@using Aerolinea.Models;
@{
    ViewBag.Title = "Actualizar lista";
    Logic lg = new Logic();
    Layout = lg.ObtenerLayout(lg.GetUserType());
}

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="form-inline" role="form">
            <div class="form-group">
                @Html.LabelFor(model => model.NumSerie, new { @class = "option" })
                @Html.TextBoxFor(model => model.NumSerie, new { @class = "form-control", @Value = Model.NumSerie })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Modelo, new { @class = "option" })
                @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control", @placeholder = "Ejm: Boeing 747.." })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Capacidad, new { @class = "option" })
                @Html.TextBoxFor(model => model.Capacidad, new { @class = "form-control", @Value = Model.Capacidad, @placeholder = "Capacidad del Avion.." })
            </div>

            <div class="form-control-static">
                <input type="submit" class="btn btn-primary" value="Actualizar" />
            </div>
        </div>
    }
</div>

Aerolinea/Views/Avion/MostrarAviones.cshtml
@model Aerolinea.Models.MostrarViewModels.MostrarAvionesViewModel
@using Aerolinea.Models;
@{
    ViewBag.Title = "Lista de Aviones";
    Logic lg = new Logic();
    Layout = lg.ObtenerLayout(lg.GetUserType());
}

@if (lg.GetUserType() == 1 || lg.GetUserType() == 2)
{
    <div class="jumbotron">
        @Html.ActionLink("Registrar", "RegistrarAvion", "Administrar")
    </div>
}

<div>
    <h3>Aviones</h3>
    @{
        if (Model.listAvi.Count == 0)
        {
            <div class="jumbotron">
                <p>No hay aviones registrados</p>
            </div>
        }
        else
        {

            <div class="row">
                <div class="col-md-10 col-lg-offset-1">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-bordered table-condensed">
                            <tr class="text-center active">
                                <th>Numero de serie</th>
                                <th>Nombre/Modelo</th>
                                <th>Capacidad</th>
                                <th>Asientos</th>
                                <th>Actualizar Avion</th>
                                <th>Eliminar Avion</th>
                            </tr>
                            @foreach (var avion in Model.listAvi)
                            {
                                if (avion.Asientos.Count == 0)
                                {
                                    <tr>
                                        <td>@avion.NumSerie</td>
                                        <td>@avion.Modelo</td>
                                        <td>@avion.Capacidad</td>
                                        <!--Seccion Extra para los valores especificos de los aviones-->
                                        <td>@Html.ActionLink("Ver Asientos", "MostrarAsientos", "Asiento", new { id = avion.AvionID }, null)</td>
                                        <td>@Html.ActionLink("Editar", "ActualizarAvion", "Avion", new { id = avion.AvionID }, null)</td>
                                        <td>@Html.ActionLink("Eliminar", "EliminarAvion", "Avion", new { id = avion.AvionID }, null)</td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td>@avion.NumSerie</td>
                                        <td>@avion.Modelo</td>
                                        <td>@avion.Capacidad</td>
                                        <!--Seccion Extra para los valores especificos de los aviones-->
                                        <td>@Html.ActionLink("Ver Asientos", "MostrarAsientos", "Asiento", new { id = avion.AvionID }, null)</td>
                                        <td>@Html.ActionLink("Editar", "ActualizarAvion", "Administrar", new { id = avion.AvionID }, null)</td>
                                        <td>No se pueden eliminar aviones con asientos.</td>
                                    </tr>
                                }
                            }
                        </table>
                    </div>
                </div>
            </div>
        }
    }

</div>

Aerolinea/Views/Avion/RegistrarAvion.cshtml
@model Aerolinea.Models.RegistrarAvionViewModel
@using Aerolinea.Models;
@{
    ViewBag.Title = "Registar Avion";
    Logic lg = new Logic();
    Layout = lg.ObtenerLayout(lg.GetUserType());
}

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="form-inline" role="form">
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Detalles del Avion</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.NumSerie, new { @class = "option" })
                    @Html.TextBoxFor(model => model.NumSerie, new { @class = "form-control", @Value = Model.NumSerie, @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.NumSerie)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Modelo, new { @class = "option" })
                    @Html.TextBoxFor(model => model.Modelo, new { @class = "form-control", @placeholder = "Ejm: Boeing 747.." })
                    @Html.ValidationMessageFor(model => model.Modelo)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Capacidad, new { @class = "option" })
                    @Html.TextBoxFor(model => model.Capacidad, new { @class = "form-control", @placeholder = "Capacidad.." })
                    @Html.ValidationMessageFor(model => model.Capacidad)
                </div>

                <div class="form-control-static">
                    <input type="submit" class="btn btn-primary" value="Registrar" />
                </div>
            </fieldset>
        </div>
    }
</div>