Aerolinea/Models/PaisViewModels/RegistrarPaisViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aerolinea.Models.PaisViewModels
{
    public class RegistrarPaisViewModel
    {
        [Required(ErrorMessage ="Campo requerido.")]
        [Display(Name = "Nombre del Pais")]
        public string Nombre { set; get; }
        /*Para actualizar NADA MAS*/
        public int PaisID { set; get; }
    }
}

Aerolinea/Controllers/PaisController.cs
using Aerolinea.DA;
using Aerolinea.DA.Entities;
using Aerolinea.Models.PaisViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aerolinea.Controllers
{
    public class PaisController : Controller
    {
        private AerolineaContext db = new AerolineaContext();

        #region Get Methods
        
        public ActionResult RegistrarPais()
        {
            return View();
        }

        public ActionResult MostrarPaises()
        {
            var model = new MostrarPaisesViewModel();
            model.listaPaises = db.pais.ToList();
            return View(model);
        }

        public ActionResult ActualizarPais(int id)
        {
            var model = new RegistrarPaisViewModel();
            var modelView = db.pais.SingleOrDefault(x => x.PaisID == id);
            model.Nombre = modelView.Nombre;
            model.PaisID = id;//OJO
            return View(model);
        }

        public ActionResult EliminarPais(int id)
        {
            var pais = db.pais.SingleOrDefault(x => x.PaisID == id);
            db.pais.Attach(pais);
            db.pais.Remove(pais);
            db.SaveChanges();
            return RedirectToAction("MostrarPaises");
        }

        #endregion


        #region Post Methods

        [HttpPost]
        public ActionResult RegistrarPais(RegistrarPaisViewModel model)
        {
            var pais = new Pais
            {
                Nombre = model.Nombre
            };
            db.pais.Add(pais);
            db.SaveChanges();
            return RedirectToAction("MostrarPaises");
        }

        public ActionResult ActualizarPais(RegistrarPaisViewModel model)
        {
            var pais = db.pais.SingleOrDefault(x => x.PaisID == model.PaisID);
            pais.Nombre = model.Nombre;
            db.Entry(pais).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("MostrarPaises");
        }

        #endregion
    }
}

Aerolinea/Views/Pais/ActualizarPais.cshtml
@model Aerolinea.Models.PaisViewModels.RegistrarPaisViewModel
@{
    ViewBag.Title = "Actualizar Pais";
    Layout = null;
}

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="form-inline" role="form">
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, new { @class = "option" })
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @Value = Model.Nombre, @placeHolder = "Nombre del Pias.. Ejm: ''Costa Rica''" })
            </div>

            <div class="form-control-static">
                <input type="submit" class="btn btn-primary" value="Actualizar" />
            </div>
        </div>
    }
</div>

Aerolinea/Views/Pais/MostrarPaises.cshtml
@model Aerolinea.Models.PaisViewModels.MostrarPaisesViewModel
@{
    ViewBag.Title = "Listas Paises";
    Layout = null;
}

<!--Hay que validar que los tipos no vean este atributo-->
<div class="jumbotron">
    @Html.ActionLink("Registrar", "RegistrarPais", "Pais")
</div>
<!--Hay que validar que los tipos no vean este atributo-->

<div>
    <h3>Paises</h3>
    @{
        if (Model.listaPaises.Count == 0)
        {
            <div class="jumbotron">
                <p>No hay paises registrados</p>
            </div>
        }
        else
        {

            <div class="row">
                <div class="col-md-10 col-lg-offset-1">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-bordered table-condensed">
                            <tr class="text-center active">
                                <th>Nombre</th>
                                <th>Actualizar Pais</th>
                                <th>Eliminar Pais</th>
                            </tr>
                            @foreach (var pais in Model.listaPaises)
                            {
                                <tr>
                                    <td>@pais.Nombre</td>
                                    <!--Seccion Extra para los valores especificos de los paises-->
                                    <td>@Html.ActionLink("Editar", "ActualizarPais", "Pais", new { id = pais.PaisID }, null)</td>
                                    <td>@Html.ActionLink("Eliminar", "EliminarPais", "Pais", new { id = pais.PaisID }, null)</td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        }
    }

</div>

Aerolinea/Views/Pais/RegistrarPais.cshtml
@model Aerolinea.Models.PaisViewModels.RegistrarPaisViewModel
@{
    ViewBag.Title = "Registrar Pais";
    Layout = null;
}

<div class="container">
    @using (Html.BeginForm())
    {
        <div class="form-inline" role="form">
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Detalles del Pais</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, new { @class = "option" })
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @Value = Model.Nombre, @readonly = "readonly", @placeHolder = "Nombre del Pias.. Ejm: ''Costa Rica''" })
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>

                <div class="form-control-static">
                    <input type="submit" class="btn btn-primary" value="Registrar" />
                </div>
            </fieldset>
        </div>
    }
</div>